# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/coral/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter coral flame,$(TARGET_DEVICE)),)

endif
