# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/redfin/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter redfin bramble,$(TARGET_DEVICE)),)

endif
